# k8s/monitoring/grafana-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: microservices
type: Opaque
data:
  admin-password: YWRtaW4xMjM= # base64 encoded "admin123"
