server:
  port: 8082
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${spring.application.instance_id:${random.value}}"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

# Security JWT
security:
  jwt:
    secret-base64: "2OhDTRAUQm3JIQ5oqDQJ7A5+wlkN63Wm2WeN8hLLhZY="
    ttl-seconds: 3600

# Feign configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full
  hystrix:
    enabled: true

# Resilience4j configuration
resilience4j:
  circuitbreaker:
    instances:
      user-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
  retry:
    instances:
      user-service:
        max-attempts: 3
        wait-duration: 1s

logging:
  level:
    com.example.authservice.client: DEBUG
    feign: DEBUG
    io.github.resilience4j: DEBUG
