server:
  port: 8082
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Security JWT
security:
  jwt:
    secret-base64: "2OhDTRAUQm3JIQ5oqDQJ7A5+wlkN63Wm2WeN8hLLhZY="
    ttl-seconds: 3600

# Feign configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full
  hystrix:
    enabled: true

logging:
  level:
    com.example.authservice.client: DEBUG
    feign: DEBUG