server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**, /roles/**
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**
            # chặn internal API không public
            - id: block-internal
              uri: no://op
              predicates:
                - Path=/internal/**
              filters:
                - name: SetStatus
                  args:
                    status: 403
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${spring.application.instance_id:${random.value}}"

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    display-operation-id: true
    default-models-expand-depth: 1
    default-model-expand-depth: 1
    urls:
      - name: "User Service"
        url: "/user-service/v3/api-docs"
        display-name: "User Service API"
      - name: "Auth Service"
        url: "/auth-service/v3/api-docs"
        display-name: "Auth Service API"
      - name: "Gateway"
        url: "/v3/api-docs"
        display-name: "API Gateway"
    url: "/v3/api-docs"
    persist-authorization: true
  show-actuator: false

# Logging for debugging
logging:
  level:
    org.springframework.cloud.gateway: TRACE
  pattern:
    level: "%5p [traceId=%X{traceId} spanId=%X{spanId} reqId=%X{X-Request-Id}]"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: true
  otlp:
    tracing:
      endpoint: http://tempo-distributor.monitoring.svc:4317

# jWT
security:
  jwt:
    secret-base64: "2OhDTRAUQm3JIQ5oqDQJ7A5+wlkN63Wm2WeN8hLLhZY="
