# k8s/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices
data:
  POSTGRES_DB: "userdb"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  REDIS_PASSWORD: ""
